User.create!([ { email: 'disregard@example.com', password: 'asdfjkl;'} ])
User.create!([ { email: 'test@example.com', password: 'asdfjkl;'} ])

Category.create!([
  { name: 'new item - category pending' },
  { name: 'destination spas' },
  { name: 'hotels' },
  { name: 'subway sandwich restaurants' },
  { name: 'u.s. cell phone carriers' },
  { name: 'sprint smart phones' },
  { name: 't-mobile smart phones' },
  { name: 'verizon smart phones' },
  { name: 'smart phones (all car)' },
  { name: 'coffeehouses' },
  { name: 'online web development courses' },
  { name: 'online review websites' },
  { name: 'coworking spaces' },
  { name: 'movie rentals' },
  { name: 'web hosting services' },
  { name: 'toyotas' },
  { name: 'airlines' },
  { name: 'rental cars' },
  { name: 'dating sites' },
  { name: 'dating apps (i)' },
  { name: 'dating apps (an)' },
  { name: 'video editing software' },
  { name: 'california health insurance plans' },
  { name: 'ridesharing services' },
  { name: 'nextspace memberships' },
  { name: 'air conditioners' },
  { name: 'air purifiers' },
  { name: 'blenders' },
  { name: 'clothes dryers' },
  { name: 'coffeemakers' },
  { name: 'cooktops & wall ovens' },
  { name: 'dehumidifiers' },
  { name: 'dishwashers' },
  { name: 'food processors & choppers' },
  { name: 'freezers' },
  { name: 'garbage disposers' },
  { name: 'humidifiers' },
  { name: 'juicers' },
  { name: 'kitchen ranges' },
  { name: 'meat thermometers' },
  { name: 'microwave ovens' },
  { name: 'mixers' },
  { name: 'range hoods' },
  { name: 'refrigerator thermometers' },
  { name: 'refrigerators' },
  { name: 'space heaters' },
  { name: 'steam irons' },
  { name: 'steam mops' },
  { name: 'thermostats' },
  { name: 'toasters' },
  { name: 'vacuum cleaners' },
  { name: 'washing machines' },
  { name: 'wet/dry vacuums' },
  { name: 'wine chillers' },
  { name: 'blu-ray players' },
  { name: 'camcorders' },
  { name: 'dvd players' },
  { name: 'headphones' },
  { name: 'home theater systems & soundbars' },
  { name: 'mp3 players' },
  { name: 'streaming media players & services' },
  { name: 'wi-fi & bluetooth speaker systems' },
  { name: 'computer backup systems' },
  { name: 'computer monitors' },
  { name: 'printers' },
  { name: 'security software' },
  { name: 'tablets' },
  { name: 'telecom services' },
  { name: 'wireless routers' },
  { name: 'digital cameras' },
  { name: 'digital picture frames' },
  { name: 'interchangeable & slr lenses' },
  { name: 'home office' },
  { name: 'paper shredders' },
  { name: 'bluetooth headsets' },
  { name: 'cell phones & services' },
  { name: 'cordless phones' },
  { name: 'e-book readers' },
  { name: 'hiking gps' },
  { name: 'mobile security software' },
  { name: 'batteries' },
  { name: 'mattresses' },
  { name: 'pillows' },
  { name: 'sheets' },
  { name: 'showerheads' },
  { name: 'toilet paper' },
  { name: 'toilets' },
  { name: 'co & smoke alarms' },
  { name: 'countertops' },
  { name: 'decking' },
  { name: 'door locks' },
  { name: 'entry doors' },
  { name: 'faucets' },
  { name: 'fire extinguishers' },
  { name: 'flooring' },
  { name: 'generators' },
  { name: 'glues' },
  { name: 'home windows' },
  { name: 'ladders' },
  { name: 'lead test kits' },
  { name: 'lightbulbs' },
  { name: 'paints' },
  { name: 'radon test kits' },
  { name: 'roofing' },
  { name: 'siding' },
  { name: 'sinks' },
  { name: 'wood stains' },
  { name: 'kitchen cabinets' },
  { name: 'kitchen cookware' },
  { name: 'kitchen knives' },
  { name: 'water filters' },
  { name: 'gas grills' },
  { name: 'tools & power equipment' },
  { name: 'chain saws' },
  { name: 'circular saws' },
  { name: 'cordless drills & tool kits' },
  { name: 'lawn mowers & tractors' },
  { name: 'leaf blowers' },
  { name: 'miter & table saws' },
  { name: 'snow blowers' },
  { name: 'string trimmers' },
  { name: 'baby clothes' },
  { name: 'baby food' },
  { name: 'baby formulas' },
  { name: 'baby jumpers' },
  { name: 'baby monitors' },
  { name: 'baby swings' },
  { name: 'baby walkers' },
  { name: 'backpack carriers' },
  { name: 'bassinets' },
  { name: 'bike trailers' },
  { name: 'bouncer seats' },
  { name: 'breast pumps' },
  { name: 'car seats' },
  { name: 'changing tables' },
  { name: 'crib bedding' },
  { name: 'crib mattresses' },
  { name: 'cribs' },
  { name: 'diaper bags' },
  { name: 'diaper pails' },
  { name: 'diapers' },
  { name: 'gliders & rocking chairs' },
  { name: 'high chairs' },
  { name: 'humidifiers for your baby' },
  { name: 'nursing bras' },
  { name: 'pacifiers' },
  { name: 'play yards' },
  { name: 'safety gates' },
  { name: 'shopping cart covers' },
  { name: 'strollers' },
  { name: 'thermometers' },
  { name: 'backpacks' },
  { name: 'toys' },
  { name: 'credit cards' },
  { name: 'prepaid cards' },
  { name: 'rewards cards' },
  { name: 'store credit cards' },
  { name: 'car insurance' },
  { name: 'homeowners insurance' },
  { name: 'brokerage services' },
  { name: 'appliance stores' },
  { name: 'computer stores' },
  { name: 'customer service' },
  { name: 'electronics stores' },
  { name: 'extended warranties' },
  { name: 'eyeglass stores' },
  { name: 'outlet stores' },
  { name: 'pharmacies' },
  { name: 'retail stores' },
  { name: 'shopping websites' },
  { name: 'sporting goods stores' },
  { name: 'supermarkets' },
  { name: 'airline travel' },
  { name: 'hotel rooms' },
  { name: 'activity trackers' },
  { name: 'bike helmets' },
  { name: 'blood glucose meters' },
  { name: 'blood pressure monitors' },
  { name: 'electric razors' },
  { name: 'ellipticals' },
  { name: 'exercise bikes' },
  { name: 'flat irons' },
  { name: 'hair dryers' },
  { name: 'heart-rate monitors' },
  { name: 'pedometers' },
  { name: 'scales' },
  { name: 'treadmills' },
  { name: 'suvs' },
  { name: 'sedans' },
  { name: 'small cars' },
  { name: 'minivans' },
  { name: 'hybrids and electric vehicles' },
  { name: 'pickup trucks' },
  { name: 'convertibles' },
  { name: 'wagons' },
  { name: 'sports cars' },
  { name: 'luxury cars' },
  { name: 'laptop computers' },
  { name: 'desktop computers' },
  { name: 'casual dining restaurants' },
  { name: 'drug and alcohol rehabs' },
  { name: 'home loans' }
])
Item.create!([
  { name: '7-eleven', url: 'http://www.7-eleven.com', user_id: 503_854_370 },
  { name: 'ace hardware', url: 'http://www.acehardware.com', user_id: 503_854_370 },
  { name: 'advance auto parts', url: 'http://www.advanceautoparts.com', user_id: 503_854_370 },
  { name: 'albertsons', url: 'http://www.albertsons.com', user_id: 503_854_370 },
  { name: 'aldi', url: 'http://www.aldi.com', user_id: 503_854_370 },
  { name: 'amazon.com', url: 'http://www.amazon.com/', user_id: 503_854_370 },
  { name: 'american', url: 'http://www.aa.com/', user_id: 503_854_370 },
  { name: 'angelpad', url: 'http://angelpad.org/', user_id: 503_854_370 },
  { name: 'apple', url: 'http://www.apple.com', user_id: 503_854_370 },
  { name: 'at&t wireless', url: 'http://www.att.com/', user_id: 503_854_370 },
  { name: 'autozone', url: 'http://www.autozone.com', user_id: 503_854_370 },
  { name: 'avis', url: 'http://www.avis.com', user_id: 503_854_370 },
  { name: 'bank of america', url: 'http://www.bankofamerica.com', user_id: 503_854_370 },
  { name: 'barnes & noble', url: 'http://www.barnesandnoble.com/', user_id: 503_854_370 },
  { name: 'bed bath & beyond', url: 'http://www.bedbathandbeyond.com/', user_id: 503_854_370 },
  { name: 'belk', url: 'http://www.belk.com', user_id: 503_854_370 },
  { name: 'best buy', url: 'http://www.bestbuy.com', user_id: 503_854_370 },
  { name: 'best western', url: 'http://www.bestwestern.com', user_id: 503_854_370 },
  { name: 'big lots', url: 'http://www.biglots.com', user_id: 503_854_370 },
  { name: 'blank spaces ', url: 'http://www.blankspaces.com', user_id: 503_854_370 },
  { name: 'blockbuster', url: 'http://www.blockbuster.com', user_id: 503_854_370 },
  { name: "bloomin' brands", url: 'http://www.bloominbrands.com', user_id: 503_854_370 },
  { name: 'bmw', url: 'http://www.bmw.com', user_id: 503_854_370 },
  { name: 'burger king worldwide', url: 'http://www.bk.com/', user_id: 503_854_370 },
  { name: 'burlington coat factory', url: 'http://www.burlingtoncoatfactory.com', user_id: 503_854_370 },
  { name: 'camry', url: 'http://www.camry.com', user_id: 503_854_370 },
  { name: 'canyon ranch', url: 'http://www.canyonranch.com', user_id: 503_854_370 },
  { name: 'chase', url: 'http://www.chase.com', user_id: 503_854_370 },
  { name: 'chipotle ', url: 'http://www.chipotle.com', user_id: 503_854_370 },
  { name: 'citibank', url: 'http://www.citibank.com', user_id: 503_854_370 },
  { name: 'coffee bean and tea leaf', url: 'http://www.coffeebean.com/', user_id: 503_854_370 },
  { name: 'coke', url: 'http://www.coke.com', user_id: 503_854_370 },
  { name: 'coloft', url: 'http://www.coloft.com', user_id: 503_854_370 },
  { name: 'costco', url: 'http://www.costco.com', user_id: 503_854_370 },
  { name: 'cvs', url: 'http://www.cvs.com', user_id: 503_854_370 },
  { name: "dick's sporting goods", url: 'http://www.dickssportinggoods.com/', user_id: 503_854_370 },
  { name: "dillard's", url: 'http://www.dillards.com', user_id: 503_854_370 },
  { name: 'dollar tree', url: 'http://www.dollartree.com', user_id: 503_854_370 },
  { name: 'dollar shave club', url: 'http://www.dollarshaveclub.com', user_id: 503_854_370 },
  { name: 'dreamitventures', url: 'http://www.dreamitventures.com', user_id: 503_854_370 },
  { name: "dunkin' brands", url: 'http://www.dunkindonuts.com/', user_id: 503_854_370 },
  { name: 'fedex', url: 'http://www.fedex.com', user_id: 503_854_370 },
  { name: 'felicis ventures', url: 'http://www.felicisventures.com', user_id: 503_854_370 },
  { name: 'fox', url: 'http://www.fox.com', user_id: 503_854_370 },
  { name: 'galaxy s4 ', url: 'http://www.samsung.com/', user_id: 503_854_370 },
  { name: 'gamestop', url: 'http://www.gamestop.com', user_id: 503_854_370 },
  { name: 'gap', url: 'http://www.gap.com', user_id: 503_854_370 },
  { name: 'giant eagle', url: 'http://www.gianteagle.com', user_id: 503_854_370 },
  { name: 'gillette', url: 'http://www.gillette.com', user_id: 503_854_370 },
  { name: 'h&m', url: 'http://www.hm.com', user_id: 503_854_370 },
  { name: 'hampton-inn', url: 'http://www.hampton-inn.com', user_id: 503_854_370 },
  { name: 'hertz', url: 'http://www.hertz.com', user_id: 503_854_370 },
  { name: 'hsbc', url: 'http://www.hsbc.com', user_id: 503_854_370 },
  { name: 'ikea', url: 'http://www.ikea.com', user_id: 503_854_370 },
  { name: 'ingles markets', url: 'http://www.ingles-markets.com/', user_id: 503_854_370 },
  { name: 'intel capital', url: 'http://www.intelcapital.com', user_id: 503_854_370 },
  { name: 'iphone 5s', url: 'http://www.apple.com', user_id: 503_854_370 },
  { name: 'j.c. penney', url: 'http://www.jcpenney.com', user_id: 503_854_370 },
  { name: 'jiffy lube', url: 'http://www.jiffylube.com', user_id: 503_854_370 },
  { name: 'kicklabs', url: 'http://www.kicklabs.com', user_id: 503_854_370 },
  { name: "kohl's", url: 'http://www.kohls.com', user_id: 503_854_370 },
  { name: 'kroger', url: 'http://www.kroger.com', user_id: 503_854_370 },
  { name: "macy's", url: 'http://www.macys.com', user_id: 503_854_370 },
  { name: 'mcdonalds', url: 'http://www.mcdonalds.com', user_id: 503_854_370 },
  { name: 'michaels stores', url: 'http://www.michaelsstores.com', user_id: 503_854_370 },
  { name: 'microsoft', url: 'http://www.microsoft.com', user_id: 503_854_370 },
  { name: 'miraval', url: 'http://www.miravalresorts.com', user_id: 503_854_370 },
  { name: 'motel 6', url: 'http://www.motel6.com', user_id: 503_854_370 },
  { name: 'netflix', url: 'http://www.netflix.com', user_id: 503_854_370 },
  { name: 'nextspace', url: 'http://www.nextspace.us', user_id: 503_854_370 },
  { name: 'nike', url: 'http://www.nike.com', user_id: 503_854_370 },
  { name: 'nordstrom', url: 'http://www.nordstrom.com', user_id: 503_854_370 },
  { name: 'office depot', url: 'http://www.office depot.com', user_id: 503_854_370 },
  { name: 'officemax', url: 'http://www.officemax.com', user_id: 503_854_370 },
  { name: 'peets', url: 'http://www.peets.com', user_id: 503_854_370 },
  { name: 'pepsi', url: 'http://www.pepsi.com', user_id: 503_854_370 },
  { name: 'petsmart', url: 'http://www.petsmart.com', user_id: 503_854_370 },
  { name: 'price chopper supermarkets', url: 'http://www.pricechopper.com', user_id: 503_854_370 },
  { name: 'prius', url: 'http://www.toyota.com/prius-family/', user_id: 503_854_370 },
  { name: 'qvc', url: 'http://www.qvc.com', user_id: 503_854_370 },
  { name: 'radioshack', url: 'http://www.radioshack.com', user_id: 503_854_370 },
  { name: 'rent-a-wreck', url: 'http://www.rent-a-wreck.com', user_id: 503_854_370 },
  { name: 'rite aid', url: 'http://www.riteaid.com', user_id: 503_854_370 },
  { name: 'ritz-carlton', url: 'http://www.ritz-carlton.com', user_id: 503_854_370 },
  { name: 'ross stores', url: 'http://www.rossstores.com/', user_id: 503_854_370 },
  { name: 'safeway', url: 'http://www.safeway.com', user_id: 503_854_370 },
  { name: 'save mart', url: 'http://www.savemart.com', user_id: 503_854_370 },
  { name: 'sequoia capital', url: 'http://www.sequoiacapital.com', user_id: 503_854_370 },
  { name: 'sherwin-williams', url: 'http://www.sherwin-williams.com', user_id: 503_854_370 },
  { name: 'southwest', url: 'http://www.southwest.com', user_id: 503_854_370 },
  { name: 'staples', url: 'http://www.staples.com', user_id: 503_854_370 },
  { name: 'starbucks', url: 'http://www.starbucks.com', user_id: 503_854_370 },
  { name: 'subway', url: 'http://www.subway.com', user_id: 503_854_370 },
  { name: 'taco bell', url: 'http://www.tacobell.com', user_id: 503_854_370 },
  { name: 'target', url: 'http://www.target.com', user_id: 503_854_370 },
  { name: 'techstars', url: 'http://www.techstars.com/program/', user_id: 503_854_370 },
  { name: 'tesla', url: 'http://www.teslamotors.com/', user_id: 503_854_370 },
  { name: 'the home depot', url: 'http://www.homedepot.com', user_id: 503_854_370 },
  { name: 'the sports authority', url: 'http://www.sportsauthority.com/', user_id: 503_854_370 },
  { name: 't-mobile', url: 'http://www.t-mobile.com', user_id: 503_854_370 },
  { name: 'toys-r-us', url: 'http://www.toys-r-us.com', user_id: 503_854_370 },
  { name: "trader joe's", url: 'http://www.traderjoes.com', user_id: 503_854_370 },
  { name: 'true value', url: 'http://www.truevalue.com/', user_id: 503_854_370 },
  { name: 'ups', url: 'http://www.ups.com', user_id: 503_854_370 },
  { name: 'usps (united states postal service)', url: 'http://www.usps.com', user_id: 503_854_370 },
  { name: 'valvoline', url: 'http://www.valvoline.com', user_id: 503_854_370 },
  { name: 'verizon wireless', url: 'http://www.verizon.com', user_id: 503_854_370 },
  { name: 'walgreen', url: 'http://www.walgreens.com/', user_id: 503_854_370 },
  { name: 'wal-mart', url: 'http://www.wal-mart.com', user_id: 503_854_370 },
  { name: 'wegmans food markets', url: 'http://www.wegmans.com', user_id: 503_854_370 },
  { name: "wendy's", url: 'http://www.wendys.com', user_id: 503_854_370 },
  { name: 'whole foods market', url: 'http://www.wholefoods.com', user_id: 503_854_370 },
  { name: 'winco foods', url: 'http://www.wincofoods.com', user_id: 503_854_370 },
  { name: 'y combinator', url: 'http://www.ycombinator.com', user_id: 503_854_370 },
  { name: 'zara', url: 'http://www.zara.com', user_id: 503_854_370 },
  { name: 'innout.com', url: 'http://www.in-n-out.com/', user_id: 503_854_370 },
  { name: 'godaddy', url: 'http://www.godaddy.com', user_id: 503_854_370 },
  { name: 'hostgator', url: 'http://www.hostgator.com', user_id: 503_854_370 },
  { name: 'bluehost', url: 'http://www.bluehost.com', user_id: 503_854_370 },
  { name: 'liquid web', url: 'http://www.liquidweb.com', user_id: 503_854_370 },
  { name: 'canyon ranch in tucson', url: 'http://www.canyonranch.com', user_id: 503_854_370 },
  { name: 'miraval arizona spa resort', url: 'http://www.miravalresorts.com/', user_id: 503_854_370 },
  { name: 'rancho la puerta', url: 'http://www.rancholapuerta.com', user_id: 503_854_370 },
  { name: 'oaks at ojai', url: 'http://www.oaksspa.com/', user_id: 503_854_370 },
  { name: 'golden door, the original', url: 'http://goldendoor.com/', user_id: 503_854_370 },
  { name: 'quiznos', url: 'http://www.quiznos.com', user_id: 503_854_370 },
  { name: 'jersey mikes subs', url: 'https://www.jerseymikes.com/', user_id: 503_854_370 },
  { name: 'samsung galaxy s 5 (16GB)', url: 'http://www.samsung.com/us/', user_id: 503_854_370 },
  { name: 'samsung galaxy s 4 (16GB)', url: 'http://www.samsung.com/us/', user_id: 503_854_370 },
  { name: 'apple iphone 5s (16GB)', url: 'http://www.apple.com', user_id: 503_854_370 },
  { name: 'apple iphone 5s (32GB)', url: 'http://www.apple.com', user_id: 503_854_370 },
  { name: 'google nexus 5', url: 'www.google.com', user_id: 503_854_370 },
  { name: 'nokia lumia 521', url: 'www.nokia.com', user_id: 503_854_370 },
  { name: 'lenovo', url: 'http://www.lenovo.com', user_id: 503_854_370 },
  { name: 'lynda', url: 'http://www.lynda.com', user_id: 503_854_370 },
  { name: 'treehouse', url: 'http://teamtreehouse.com/', user_id: 503_854_370 },
  { name: 'udemy', url: 'http://www.udemy.com', user_id: 503_854_370 },
  { name: 'verve', url: 'http://www.vervecoffeeroasters.com/', user_id: 503_854_370 },
  { name: 'red mountain spa resort', url: 'http://redmountainresort.com/', user_id: 503_854_370 },
  { name: 'ratestuf', url: 'http://www.ratestuf.org/', user_id: 503_854_370 },
  { name: 'yelp', url: 'http://www.yelp.com', user_id: 503_854_370 },
  { name: 'cross campus', url: 'http://www.crosscamp.us/', user_id: 503_854_370 },
  { name: 'xnxx.com', url: 'http://en.wikipedia.org/wiki/Pornography', user_id: 503_854_370 },
  { name: 'pornhub', url: 'http://en.wikipedia.org/wiki/Pornography', user_id: 503_854_370 },
  { name: 'youporn', url: 'http://en.wikipedia.org/wiki/Pornography', user_id: 503_854_370 },
  { name: 'naughty america', url: 'http://en.wikipedia.org/wiki/Pornography', user_id: 503_854_370 },
  { name: 'mercedes-benz', url: 'http://www.mercedes-benz.com', user_id: 503_854_370 },
  { name: 'ford', url: 'http://www.ford.com', user_id: 503_854_370 },
  { name: 'honda', url: 'http://www.honda.com', user_id: 503_854_370 },
  { name: 'toyota', url: 'http://www.toyota.com', user_id: 503_854_370 },
  { name: 'audi', url: 'http://www.audi.com', user_id: 503_854_370 },
  { name: 'mitsubishi', url: 'http://www.mitsubishi.com', user_id: 503_854_370 },
  { name: 'sienna', url: 'http://www.toyota.com/sienna', user_id: 503_854_370 },
  { name: 'corolla', url: 'http://www.toyota.com/corolla/', user_id: 503_854_370 },
  { name: 'tacoma', url: 'http://www.toyota.com/tacoma/', user_id: 503_854_370 },
  { name: 'avalon', url: 'http://www.toyota.com/avalon', user_id: 503_854_370 },
  { name: 'yaris', url: 'http://www.toyota.com/yaris/', user_id: 503_854_370 },
  { name: '4runner', url: 'http://www.toyota.com/4runner', user_id: 503_854_370 },
  { name: 'highlander', url: 'http://www.toyota.com/highlander/', user_id: 503_854_370 },
  { name: 'alaska', url: 'http://www.alaskaair.com/', user_id: 503_854_370 },
  { name: 'delta', url: 'http://www.delta.com/', user_id: 503_854_370 },
  { name: 'enterprise', url: 'http://www.enterprise.com', user_id: 503_854_370 },
  { name: 'match.com', url: 'http://www.match.com/', user_id: 503_854_370 },
  { name: 'okcupid.com', url: 'http://www.okcupid.com/home', user_id: 503_854_370 },
  { name: 'pof.com (plenty of fish)', url: 'www.pof.com', user_id: 503_854_370 },
  { name: 'whim (iphone app)', url: 'www.whim.la', user_id: 503_854_370 },
  { name: 'plenty of fish (iphone app)', url: 'www.pof.com', user_id: 503_854_370 },
  { name: 'grindr (iphone app)', url: 'http://grindr.com/', user_id: 503_854_370 },
  { name: 'whim (android app)', url: 'www.whim.la', user_id: 503_854_370 },
  { name: 'grindr (android app)', url: 'http://grindr.com/', user_id: 503_854_370 },
  { name: 'plenty of fish (android app)', url: 'www.pof.com', user_id: 503_854_370 },
  { name: 'avid', url: 'http://www.avid.com/US/', user_id: 503_854_370 },
  { name: 'adobe premiere', url: 'http://www.adobepremiere.com', user_id: 503_854_370 },
  { name: 'final cut pro', url: 'http://www.apple.com/final-cut-pro/', user_id: 503_854_370 },
  { name: 'imovie', url: 'https://www.apple.com/mac/imovie/', user_id: 503_854_370 },
  { name: 'vegas pro', url: 'http://www.sonycreativesoftware.com/vegaspro', user_id: 503_854_370 },
  { name: 'REI', url: 'http://www.REI.com', user_id: 503_854_370 },
  { name: 'L.A. Care Covered Bronze 60 HMO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'Molina Bronze 60 HMO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'Anthem Bronze 60 EPO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'Anthem Bronze 60 Health Savings Account EPO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'Health Net Enhanced Silver 73 HMO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'Anthem Enhanced Silver 73 HMO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'Molina Enhanced Silver 73 HMO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'L.A. Care Covered Enhanced Silver 73 HMO', url: 'http://www.coveredca.com/', user_id: 503_854_370 },
  { name: 'esalen', url: 'http://www.esalen.org', user_id: 503_854_370 },
  { name: 'car', url: 'http://www.car.com', user_id: 503_854_370 },
  { name: 'marijuana', url: 'http://en.wikipedia.org/wiki/Cannabis_(drug)', user_id: 503_854_370 },
  { name: 'lyft', url: 'http://www.lyft.com', user_id: 503_854_370 },
  { name: 'uber', url: 'http://www.uber.com', user_id: 503_854_370 },
  { name: 'iphone', url: 'http://www.apple.com/', user_id: 503_854_370 },
  { name: 'samsung galaxy 5', url: 'http://www.samsung.com/us/', user_id: 503_854_370 },
  { name: 'facebook', url: 'https://www.facebook.com/', user_id: 1 },
  { name: 'Apple MacBook Pro 15-inch (2013)', url: '', user_id: 1 },
  { name: 'Apple MacBook Pro 13-inch (2013)', url: '', user_id: 1 },
  { name: 'Asus Transformer Book T100TA (64GB)', url: '', user_id: 1 },
  { name: 'HP Chromebook 11 (Verizon LTE)', url: '', user_id: 1 },
  { name: 'Dell Latitude E7440 Touch', url: '', user_id: 1 },
  { name: 'Digital Storm Krypton', url: '', user_id: 1 },
  { name: 'Lenovo G580', url: '', user_id: 1 },
  { name: 'Lenovo ThinkPad X240', url: '', user_id: 1 },
  { name: 'Acer Aspire E1-510P-2671', url: '', user_id: 1 },
  { name: 'MSI GS70 Stealth (GS70 2OD-002US)', url: '', user_id: 1 },
  { name: 'laptop computers', url: '', user_id: 503_854_370 },
  { name: 'laptop', url: '', user_id: 503_854_370 },
  { name: 'desination spas', url: '', user_id: 503_854_370 },
  { name: 'restaurants', url: '', user_id: 551_528_600 },
  { name: 'san francisco', url: '', user_id: 608_873_296 },
  { name: 'the bike hut san francisco', url: '', user_id: 608_873_296 },
  { name: 'hosting services', url: '', user_id: 503_854_370 },
  { name: 'network solutions', url: '', user_id: 503_854_370 },
  { name: "applebee's", url: '', user_id: 503_854_370 },
  { name: 'baja fresh', url: '', user_id: 503_854_370 },
  { name: 'benihana', url: '', user_id: 503_854_370 },
  { name: 'big boy', url: '', user_id: 503_854_370 },
  { name: 'the cheesecake factory', url: '', user_id: 503_854_370 },
  { name: 'outback steakhouse', url: '', user_id: 503_854_370 },
  { name: "p. f. chang's china bistro", url: '', user_id: 503_854_370 },
  { name: 'sizzler', url: '', user_id: 503_854_370 },
  { name: 'coffee', url: '', user_id: 503_854_370 },
  { name: 'tea', url: '', user_id: 503_854_370 },
  { name: 'crumbcakes', url: '', user_id: 503_854_370 },
  { name: 'applebee', url: '', user_id: 503_854_370 },
  { name: 'ritz carlton', url: '', user_id: 503_854_370 },
  { name: 'youporn.com', url: 'http://en.wikipedia.org/wiki/Pornography', user_id: 503_854_370 },
  { name: 'applebees', url: '', user_id: 503_854_370 },
  { name: 'state farm', url: 'https://www.statefarm.com/', user_id: 503_854_370 },
  { name: 'automobile club of southern california', url: '', user_id: 503_854_370 },
  { name: 'american family insurance group', url: '', user_id: 503_854_370 },
  { name: 'geico', url: 'https://www.geico.com/', user_id: 503_854_370 },
  { name: 'nationwide mutual', url: '', user_id: 503_854_370 },
  { name: 'travelers', url: '', user_id: 503_854_370 },
  { name: 'liberty mutual', url: '', user_id: 503_854_370 },
  { name: 'allstate', url: '', user_id: 503_854_370 },
  { name: 'metlife', url: '', user_id: 503_854_370 },
  { name: 'progressive', url: 'http://www.progressive.com/', user_id: 503_854_370 },
  { name: 'promises', url: '', user_id: 503_854_370 },
  { name: 'paradise recovery center', url: '', user_id: 503_854_370 },
  { name: 'solutions recovery center', url: '', user_id: 503_854_370 },
  { name: 'beachway therapy center', url: '', user_id: 503_854_370 },
  { name: 'betty ford', url: '', user_id: 503_854_370 },
  { name: 'hazelden', url: '', user_id: 503_854_370 },
  { name: 'sierra tucson', url: '', user_id: 503_854_370 },
  { name: 'the caron foundation', url: '', user_id: 503_854_370 },
  { name: 'discover home loans', url: '', user_id: 503_854_370 },
  { name: 'quicken loans', url: '', user_id: 503_854_370 },
  { name: 'shampoo wella', url: '', user_id: 714_090_325 },
  { name: "cow's end", url: '', user_id: 503_854_370 },
  { name: 'laravel', url: '', user_id: 503_854_370 },
  { name: 'symfony', url: '', user_id: 503_854_370 },
  { name: 'hosting', url: '', user_id: 503_854_370 },
  { name: 'dreamhost', url: '', user_id: 503_854_370 },
  { name: 'cars', url: '', user_id: 503_854_370 },
  { name: 'batman', url: '', user_id: 503_854_370 },
  { name: 'superman', url: '', user_id: 503_854_370 },
  { name: 'virgin', url: 'https://www.virginamerica.com/', user_id: nil },
  { name: 'cruzio', url: 'http://cruzio.com/', user_id: 19 }
])

# items need a category to be displayed as a result of the sql
(Item.all).each do |item|
  CategoriesItem.create!([{ item_id: item.id, category_id: Category.find_by_name("new item - category pending").id }])
end

CategoriesItem.create!([{ item_id: Item.find_by_name('southwest').id, category_id: Category.find_by_name('airlines').id }])
CategoriesItem.create!([{ item_id: Item.find_by_name('delta').id, category_id: Category.find_by_name('airlines').id }])
CategoriesItem.create!([{ item_id: Item.find_by_name('virgin').id, category_id: Category.find_by_name('airlines').id }])
CategoriesItem.create!([{ item_id: Item.find_by_name('american').id, category_id: Category.find_by_name('airlines').id }])

CategoriesItem.create!([{ item_id: Item.find_by_name('geico').id, category_id: Category.find_by_name('car insurance').id }])
CategoriesItem.create!([{ item_id: Item.find_by_name('progressive').id, category_id: Category.find_by_name('car insurance').id }])

CategoriesItem.create!([{ item_id: Item.find_by_name('hazelden').id, category_id: Category.find_by_name('drug and alcohol rehabs').id }])
CategoriesItem.create!([{ item_id: Item.find_by_name('promises').id, category_id: Category.find_by_name('drug and alcohol rehabs').id }])
CategoriesItem.create!([{ item_id: Item.find_by_name('sierra tucson').id, category_id: Category.find_by_name('drug and alcohol rehabs').id }])
CategoriesItem.create!([{ item_id: Item.find_by_name('betty ford').id, category_id: Category.find_by_name('drug and alcohol rehabs').id }])

# default rating
(Item.all).each do |item|
  Rating.create!([{ user_id: User.first.id, item_id: item.id}])
end

2250.times do
  Rating.create!([{ user_id: User.first.id, item_id: Item.all.sample.id, x_rating: rand(0.0..1.0), y_rating: rand(0.0..1.0)}])
end
